title: Celerity Consulting
email: info@celerityconsulting.com
favicon: /images/cg-logo-32x32.png
logo: /images/cg-logo-93x54.png
copyright: "2021 Celerity Consulting Group, Inc. All Rights Reserved."
google_site_verification: "LNR7yDdDdi9bNUyr6B-xZc-aoYZXEwRGJbFALmbO4JU"
google_analytics: "UA-57408603-1"
description: >-
  Accelerate product development.
  Create high performance teams.
  Jumpstart organizational change.
url: "https://www.celerityconsulting.com"
twitter_username: celeritycg
linkedin_username: celerity-consulting-group-llc
# github_username:  celerityconsulting

theme: minima
plugins:
  - jekyll-feed
