title: Celerity Consulting
email: info@celerityconsulting.com
description: >- # this means to ignore newlines until "baseurl:"
  Celerity Consulting brings the power of Risk Up Front to accelerate,
  and jumpstart your projects. We focus on helping organizations of all
  sizes create high-performance project teams.
twitter_username: celeritycg
github_username:  celerityconsulting

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
